# Clean clone → working build:
#
#     make bootstrap && make generate && make test
#
# There is deliberately no `mise` step: it is not installed on the target machine and the
# toolchain here is whatever Xcode ships (Swift 6.2.3 / Xcode 26.2 at time of writing).

SHELL := /bin/bash
MODELS_DIR ?= $(HOME)/Library/Application Support/Kotiba/models

.PHONY: help bootstrap check-models generate build test golden-check lint clean doctor app install run probe copies

help:
	@grep -E '^[a-z-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN{FS=":.*?## "}{printf "  %-14s %s\n",$$1,$$2}'

doctor: ## Check the toolchain this repo needs
	@swift --version | head -2
	@xcodegen --version || echo "MISSING: brew install xcodegen"
	@echo "models dir: $(MODELS_DIR)"

bootstrap: ## Fetch every model in Scripts/Manifest.json and verify its sha256 (OPTIONAL=1: Arabic's too)
	@python3 Scripts/fetch-models.py --dest "$(MODELS_DIR)" $(if $(OPTIONAL),--optional,)

check-models: ## Prove every model is still fetchable, without downloading 1.2 GB
	@python3 Scripts/fetch-models.py --dest "$(MODELS_DIR)" --check

# The Apple Team ID is per-person and is not in the repo. A contributor writes
# `DEVELOPMENT_TEAM = ABCDE12345` into Config/Local.xcconfig (git-ignored). To keep one copy for
# every checkout and worktree, put it at ~/.config/kotiba/Local.xcconfig and this target copies it in.
# ~/.config/kotib/ is still read when the new one is absent: that is where it lived before the
# rename to Kotiba, and a missing team silently changes the signature macOS keys permissions on.
generate: ## Regenerate Kotiba.xcodeproj from project.yml (gitignored on purpose)
	@for cfg in "$(HOME)/.config/kotiba/Local.xcconfig" "$(HOME)/.config/kotib/Local.xcconfig"; do \
		if [ ! -f Config/Local.xcconfig ] && [ -f "$$cfg" ]; then \
			cp "$$cfg" Config/Local.xcconfig; echo "Config/Local.xcconfig <- $$cfg"; fi; done
	@if [ ! -f Config/Local.xcconfig ]; then \
		echo "note: no Config/Local.xcconfig - set DEVELOPMENT_TEAM there before 'make app' (see docs/SETUP.md)"; fi
	@xcodegen generate

build: ## Band 0: does it compile
	@swift build

test: ## Bands 1 and 2 — no signing, no models, no microphone — plus the golden check
	@swift test
	@$(MAKE) --no-print-directory golden-check

# windows/fixtures/golden/*.json is generated by kotiba-golden and the Windows gate asserts the
# port against it — but nothing used to regenerate it, so a Mac change that should have moved a
# fixture (or that broke the generator outright: a new AppSettings field makes it exit 1 by
# design) stayed green on both platforms. This regenerates into a scratch directory and fails on
# a generator error or on any committed fixture that differs from what the source now says.
# It never writes the committed files; `swift run kotiba-golden windows/fixtures/golden` does.
golden-check: ## Fail if windows/fixtures/golden is stale or kotiba-golden no longer runs
	@set -uo pipefail; \
	out="$$(mktemp -d)"; trap 'rm -rf "$$out"' EXIT; \
	swift build --product kotiba-golden >/dev/null || { echo "golden: kotiba-golden does not build"; exit 1; }; \
	"$$(swift build --show-bin-path)/kotiba-golden" "$$out" >/dev/null \
		|| { echo "golden: kotiba-golden failed (see the message above)"; exit 1; }; \
	stale=0; \
	for f in "$$out"/*.json; do \
		cmp -s "$$f" "windows/fixtures/golden/$$(basename "$$f")" \
			|| { echo "golden: windows/fixtures/golden/$$(basename "$$f") is stale"; stale=1; }; \
	done; \
	for f in windows/fixtures/golden/*.json; do \
		[ -f "$$out/$$(basename "$$f")" ] || { echo "golden: $$f is no longer generated"; stale=1; }; \
	done; \
	if [ "$$stale" -ne 0 ]; then \
		echo "  regenerate: swift run kotiba-golden windows/fixtures/golden, and commit the diff"; exit 1; fi; \
	echo "golden fixtures are current"

test-models: ## Band 3 — requires KOTIBA_MODEL_DIR to point at real weights
	@KOTIBA_MODEL_DIR="$(MODELS_DIR)" swift test

lint: ## Fail if KotibaCore has grown a platform dependency
	@! grep -rnE '^import (AVFoundation|CoreML|SwiftUI|UIKit|AppKit)|#if os\(' Sources/KotibaCore \
		|| { echo "KotibaCore must stay pure — move it behind a protocol in Contracts.swift"; exit 1; }
	@echo "KotibaCore is clean"

app: generate ## Build KotibaMac.app in Release
	@# The coverage settings: the scheme's test coverage otherwise instruments this Release
	@# build too (profile counters in every module). See make-dmg.sh.
	@xcodebuild -project Kotiba.xcodeproj -scheme KotibaMac -configuration Release \
		-destination 'platform=macOS' -derivedDataPath build/xcode \
		CLANG_COVERAGE_MAPPING=NO CLANG_ENABLE_CODE_COVERAGE=NO build | tail -3

# /Applications, not DerivedData. The signing identity is what TCC keys on — the designated
# requirement is `identifier "uz.kotiba.app" and ... Apple Development: …` — so grants survive a
# move and a rebuild. The path still matters for the user: an app that only exists inside
# DerivedData disappears the first time anyone runs `make clean`.
install: app ## Build Release and put it in /Applications
	@pkill -x KotibaMac 2>/dev/null || true
	@rm -rf /Applications/Kotiba.app
	@cp -R build/xcode/Build/Products/Release/KotibaMac.app /Applications/Kotiba.app
	@# The intermediate goes. It carries the same bundle id as the installed copy, so leaving
	@# it behind means a second Kotiba that can be launched by accident — two menu-bar icons,
	@# two taps on right-⌘, two racing pastes. Observed exactly that on 2026-08-08.
	@rm -rf build/xcode
	@echo "installed → /Applications/Kotiba.app"
	@echo "Grant Accessibility and Input Monitoring to *this* copy, then hold right ⌘."

run: install ## Build, install, launch
	@open /Applications/Kotiba.app

dmg: ## Build Kotiba.dmg into dist/ — Uzbek models inside, Parakeet + Qwen on first run (MODELS=1: all inside; ADHOC=1: no Apple ID/team, the public build)
	@Scripts/make-dmg.sh $(if $(ADHOC),--adhoc,) $(if $(MODELS),--with-models,) $(if $(OUT),$(OUT),)

probe: ## Measure an engine on a real clip: make probe ARGS="--engine apple clip.wav"
	@swift run -c release kotiba-probe transcribe $(ARGS)

# Any bundle other than /Applications/Kotiba.app is a second Kotiba waiting to be launched by
# accident. Same bundle id, same TCC identity, same hotkey.
copies: ## List every built copy of the app that is not the installed one
	@find . "$(HOME)/Library/Developer/Xcode/DerivedData" -maxdepth 8 -name "KotibaMac.app" \
		-type d 2>/dev/null; echo "(plus /Applications/Kotiba.app, which is the real one)"

clean:
	@rm -rf .build Kotiba.xcodeproj build
	@rm -rf "$(HOME)/Library/Developer/Xcode/DerivedData"/Kotiba-*
