#!/usr/bin/env python3
"""Fit the language decision's weights (`LanguageModel`, P4 §4) on the tuning half.

    kotiba-probe lid-features rows.jsonl feats.jsonl
    python3 Scripts/measure/fit-lid.py feats.jsonl [--C 1.0] [--write]

Reads the features `kotiba-probe lid-features` computed with the shipped KotibaCore code, keeps
the rows with `tune: true`, and fits one multinomial logistic model over the five languages:

    score(L) = A[L] · [acoustic features, 1] + Σ_{transcripts present} W[source][L] · features

Each clip is shown to the fit under every set of transcripts the session can have in hand when it
decides — none (the acoustic route), any one engine's (the routed one), any two or three (after
further opinions, `LanguagePolicy.maxEngines`) — so one set of weights is right whichever arrive. Classes are weighted to balance, so
the model carries no prior of its own: the user's (`LanguagePrior`) is added at run time.

`--write` regenerates `Sources/KotibaCore/LanguageModelWeights.swift` and
`windows/src/core/routing/language-model-weights.ts` (both platforms, byte-for-byte the same
numbers; golden route.json › lid pins them).
"""
import itertools
import json
import os
import sys

import numpy as np
from sklearn.linear_model import LogisticRegression

ORDER = ["uz", "tr", "ar", "en", "ru"]
SOURCES = ["pk", "uz", "tr", "ar"]
NA, NT = 8, 11          # acoustic features + bias; transcript features per source
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def vector(row, sources):
    x = np.zeros(NA + NT * len(SOURCES))
    x[:NA] = row["a"] + [1.0]
    for s in sources:
        i = NA + NT * SOURCES.index(s)
        x[i:i + NT] = row["t"][s]
    return x


def patterns(row):
    have = [s for s in SOURCES if s in row["t"]]
    out = [()]
    out += [(s,) for s in have]
    out += list(itertools.combinations(have, 2))
    out += list(itertools.combinations(have, 3))
    return out


# Synthetic speech (macOS voices reading another language's words, `st-tune-*`) counts this much
# of a real clip: enough to teach the fit that Parakeet's fluent English beats a voice that sounds
# Russian or Arabic, not so much that real short Arabic or Turkish starts going to English (P4 §4).
SYNTHETIC_WEIGHT = 0.2


def fit(rows, C):
    X, Y, W = [], [], []
    for r in rows:
        w = SYNTHETIC_WEIGHT if r["set"].startswith("st-tune") else 1.0
        for p in patterns(r):
            X.append(vector(r, p))
            Y.append(ORDER.index(r["lang"]))
            W.append(w)
    Y, W = np.array(Y), np.array(W)
    # Each language weighs the same in all (so the model carries no prior of its own).
    W = W * np.array([len(Y) / (5 * W[Y == y].sum()) for y in Y])
    m = LogisticRegression(C=C, max_iter=20000, fit_intercept=False)
    m.fit(np.array(X), Y, sample_weight=W)
    W = m.coef_                              # [5, NA + 4*NT]
    W = W - W.mean(axis=0, keepdims=True)    # softmax-invariant; one canonical form
    return W


def fmt(v):
    return f"{v:.6f}"


def render(W):
    acoustic = [[fmt(v) for v in W[i, :NA]] for i in range(5)]
    transcript = [[[fmt(v) for v in W[i, NA + NT * s:NA + NT * (s + 1)]] for i in range(5)]
                  for s in range(len(SOURCES))]
    head = ("GENERATED by Scripts/measure/fit-lid.py (P4 §4). Do not edit — refit and regenerate.\n"
            "Rows: uz, tr, ar, en, ru. Acoustic: log p(uz, tr, ar, en, ru, none), log seconds, 1.\n"
            "Transcript (per source: Parakeet, Uzbek, Turkish, Arabic engine): per word list\n"
            "uz, tr, ar, en, ru — log(1 + known), log(1 + not known); then unusable.")
    def rows_swift(m, indent):
        return (",\n".join(indent + "[" + ", ".join(r) + "]" for r in m))
    swift = "".join(f"// {l}\n" for l in head.split("\n")) + "\n" + (
        "extension LanguageModel {\n"
        "    /// The fitted model (P4 §4).\n"
        "    public static let fitted = LanguageModel(\n"
        "        acoustic: [\n" + rows_swift(acoustic, "            ") + ",\n        ],\n"
        "        transcript: [\n"
        + "".join("            [\n" + rows_swift(t, "                ") + ",\n            ],\n"
                  for t in transcript)
        + "        ])\n}\n")
    def rows_ts(m, indent):
        return (",\n".join(indent + "[" + ", ".join(r) + "]" for r in m))
    ts = "".join(f"// {l}\n" for l in head.split("\n")) + "\n" + (
        "/** The fitted model (P4 §4): `[language][feature]`. */\n"
        "export const LID_ACOUSTIC_WEIGHTS: readonly (readonly number[])[] = [\n"
        + rows_ts(acoustic, "  ") + ",\n];\n\n"
        "/** `[source][language][feature]`: Parakeet, Uzbek, Turkish, Arabic engine. */\n"
        "export const LID_TRANSCRIPT_WEIGHTS: readonly (readonly (readonly number[])[])[] = [\n"
        + "".join("  [\n" + rows_ts(t, "    ") + ",\n  ],\n" for t in transcript) + "];\n")
    return swift, ts


def main():
    path = sys.argv[1]
    C = float(sys.argv[sys.argv.index("--C") + 1]) if "--C" in sys.argv else 1.0
    rows = [json.loads(l) for l in open(path)]
    tune = [r for r in rows if r["tune"]]
    W = fit(tune, C)
    print(f"fitted on {len(tune)} tuning clips (C={C})")
    swift, ts = render(W)
    if "--json" in sys.argv:
        json.dump(W.tolist(), open(sys.argv[sys.argv.index("--json") + 1], "w"))
    if "--write" in sys.argv:
        for p, text in ((os.path.join(ROOT, "Sources/KotibaCore/LanguageModelWeights.swift"), swift),
                        (os.path.join(ROOT, "windows/src/core/routing/language-model-weights.ts"), ts)):
            open(p, "w").write(text)
            print("wrote", os.path.relpath(p, ROOT))
    else:
        print(swift)


if __name__ == "__main__":
    main()
