// The deterministic half of the modes, byte for byte against the Swift.
//
// `fixtures/golden/modes.json` is generated by `swift run kotiba-golden windows/fixtures/golden`,
// which RUNS `DictationCleanup`, `PunctuationProjection`, `SentenceSplitter`, `NoteLayout`,
// `SentenceGuard` and the model-free Note path of `IncrementalPolish` (C3 §7). Every row
// here is one of those calls, and a mismatch is a failing gate — the only reason a second
// implementation of these rules is allowed to exist (D-W1).

import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import type { Language } from '../../src/contracts/index.js';
import {
  DROPPABLE,
  MINIMUM_ALIGNMENT,
  OPENERS,
  checkRewrite,
  cleanUp,
  headingPrompt,
  messagePrompt,
  project,
  splitSentences,
  type PolishPrompt,
} from '../../src/core/modes/index.js';
import { checkUzbekPolishGuard, quoteSpoken, redactSpoken } from '../../src/core/text/index.js';
import { IncrementalPolish, type PromptedPolisher } from '../../src/polish/incremental.js';

interface ModesGolden {
  readonly cleanup: readonly { in: string; language: Language; out: string; outOpen: string }[];
  readonly projection: readonly { in: string; model: string; out: string; aligned: number }[];
  readonly arabicMessage: readonly { in: string; model: string; out: string; aligned: number; accepted: boolean }[];
  readonly split: readonly { in: string; sentences: string[]; rest: string; final: string[] }[];
  readonly note: readonly { in: string; language: Language; out: string }[];
  readonly noteModelled: readonly {
    in: string;
    language: Language;
    labels: Record<string, string>;
    heading: string | null;
    asked: string[];
    out: string;
    modelSentences: number;
  }[];
  readonly messageGuard: readonly {
    in: string;
    language: Language;
    rewrite: string;
    accepted: boolean;
    reason: string | null;
  }[];
  readonly uzbekGuard: readonly { polished: string; original: string; accepted: boolean; reason: string | null }[];
  readonly spokenText: {
    readonly quote: readonly { in: string; out: string }[];
    readonly redact: readonly { in: string; out: string }[];
  };
}

/**
 * The generator's `ScriptedNoteEngine`: the note classifier answers from a table (anything
 * else: POINT), every heading request gets the one heading, and what it was asked is kept.
 */
class ScriptedNoteEngine implements PromptedPolisher {
  readonly id = 'golden-scripted';
  readonly supportedLanguages: ReadonlySet<Language> = new Set<Language>(['en', 'ru', 'uz']);
  readonly asked: string[] = [];
  constructor(
    private readonly labels: Readonly<Record<string, string>>,
    private readonly heading: string | null,
  ) {}
  async generate(text: string, language: Language, prompt: PolishPrompt): Promise<string> {
    this.asked.push(text);
    const wanted = headingPrompt(language);
    if (prompt.system === wanted.system && prompt.examples === wanted.examples) {
      if (this.heading === null) throw new Error('no heading scripted');
      return this.heading;
    }
    return this.labels[text] ?? 'POINT';
  }
}

const golden = JSON.parse(
  readFileSync(join(__dirname, '../../fixtures/golden/modes.json'), 'utf8'),
) as ModesGolden;

describe('modes.json — DictationCleanup', () => {
  it('has the rows the Swift generator writes', () => {
    // 34 invented sentences, the 43 review probes of 2026-09-30, the 18 content-safety probes
    // of wip/cleanup-fix, the 120 committed Uzbek transcripts, and the 26 Turkish and Arabic
    // rows of D-11 (C4). A shorter file means the generator changed, not that the port got easier.
    expect(golden.cleanup.length).toBe(241);
    expect(golden.cleanup.filter((row) => row.language === 'tr' || row.language === 'ar')).toHaveLength(26);
  });

  it.each(golden.cleanup.map((row, index) => [index, row] as const))('row %i closes the sentence', (_index, row) => {
    expect(cleanUp(row.in, row.language)).toBe(row.out);
  });

  it.each(golden.cleanup.map((row, index) => [index, row] as const))('row %i leaves a segment open', (_index, row) => {
    expect(cleanUp(row.in, row.language, { closesFinalSentence: false })).toBe(row.outOpen);
  });
});

describe('modes.json — PunctuationProjection', () => {
  it.each(golden.projection.map((row) => [row.in, row] as const))('%s', (_label, row) => {
    const result = project(row.model, row.in);
    expect(result.text).toBe(row.out);
    // The generator writes nine decimal places.
    expect(result.aligned).toBeCloseTo(row.aligned, 8);
  });
});

describe('modes.json — Arabic Message projection (C4 §14.5)', () => {
  const mayDrop = new Set([...DROPPABLE.ar, ...(OPENERS.ar ?? [])]);
  it.each(golden.arabicMessage.map((row) => [row.in, row] as const))('%s', (_label, row) => {
    const result = project(row.model, row.in, mayDrop);
    expect(result.text).toBe(row.out);
    expect(result.aligned).toBeCloseTo(row.aligned, 8);
    expect(result.aligned >= MINIMUM_ALIGNMENT).toBe(row.accepted);
  });
});

describe('modes.json — SentenceSplitter', () => {
  it.each(golden.split.map((row) => [row.in, row] as const))('%j', (_label, row) => {
    const incremental = splitSentences(row.in, true);
    expect(incremental.sentences).toEqual(row.sentences);
    expect(incremental.rest).toBe(row.rest);
    expect(splitSentences(row.in, false).sentences).toEqual(row.final);
  });
});

describe('modes.json — Note with no model', () => {
  it.each(golden.note.map((row) => [row.in, row] as const))('%s', async (_label, row) => {
    const session = new IncrementalPolish({ behaviour: 'note', language: row.language, engine: null });
    const outcome = await session.finish(row.in);
    expect(outcome.text).toBe(row.out);
    expect(outcome.modelSentences).toBe(0);
  });
});

describe('modes.json — Note with a scripted model', () => {
  it.each(golden.noteModelled.map((row) => [row.in, row] as const))('%s', async (_label, row) => {
    const engine = new ScriptedNoteEngine(row.labels, row.heading);
    const session = new IncrementalPolish({ behaviour: 'note', language: row.language, engine });
    const outcome = await session.finish(row.in, 30_000);
    // What the model was asked, in order, pins the trimmed classifier input and the
    // heading's own input as well as the layout.
    expect(engine.asked).toEqual(row.asked);
    expect(outcome.text).toBe(row.out);
    expect(outcome.modelSentences).toBe(row.modelSentences);
  });
});

describe('modes.json — the Message sentence guard', () => {
  it.each(golden.messageGuard.map((row) => [`${row.in} → ${row.rewrite}`, row] as const))('%s', (_label, row) => {
    const reason = checkRewrite(row.rewrite, row.in, row.language, messagePrompt(row.language), DROPPABLE[row.language]);
    expect(reason === null).toBe(row.accepted);
    // The reason is a diagnostics note, and the summary redacts what it quotes: its exact
    // words matter.
    expect(reason).toBe(row.reason);
  });
});

describe('modes.json — the Uzbek polish guard', () => {
  it.each(golden.uzbekGuard.map((row) => [`${row.original} → ${row.polished}`, row] as const))('%s', (_label, row) => {
    const rejection = checkUzbekPolishGuard(row.polished, row.original);
    expect(rejection === null).toBe(row.accepted);
    expect(rejection?.reason ?? null).toBe(row.reason);
  });
});

describe('modes.json — SpokenText', () => {
  it.each(golden.spokenText.quote.map((row) => [row.in, row] as const))('quote %j', (_label, row) => {
    expect(quoteSpoken(row.in)).toBe(row.out);
  });
  it.each(golden.spokenText.redact.map((row) => [row.in, row] as const))('redact %j', (_label, row) => {
    expect(redactSpoken(row.in)).toBe(row.out);
  });
});
