#!/usr/bin/env python3
"""Regenerate the English word list that `TranscriptCheck` reads Parakeet's transcript against.

    python3 Scripts/english-words.py            # writes both platforms' copies
    python3 Scripts/english-words.py --check    # exits 1 if either copy is stale

Source: SCOWL (Spell Checker Oriented Word Lists) 2020.12.07 by Kevin Atkinson, levels 10, 20
and 35 of the English and American word lists plus the common contractions — the lists SCOWL
itself calls the "small" and "medium" dictionaries, i.e. common words and their inflections.
Licence: a permissive notice reproduced in LICENSES/SCOWL.txt (THIRD_PARTY_NOTICES.md §5).

What is kept, and why (docs/research/P2-uzbek-route-and-tail.md §2):
  * lowercase entries only — capitalised ones are proper nouns, which the check never counts;
  * no possessives (`word's`) — the lookup strips `'s` itself;
  * `i`, which SCOWL has only as `I` and which the check does count mid-sentence.

Level 35 was chosen on the tuning half of the measurement: 10 (4k words) called too much real
English "not English", 50 (62k) caught no more Uzbek than 35.
"""
import hashlib
import io
import os
import sys
import tarfile
import urllib.request

URL = "https://downloads.sourceforge.net/project/wordlist/SCOWL/2020.12.07/scowl-2020.12.07.tar.gz"
SHA256 = "5587667caa20c4891390c2d42dbb4d5c4c3f41bee77af1457ece3ba23fb859cc"
MEMBERS = [f"{kind}-words.{level}" for kind in ("english", "american") for level in (10, 20, 35)] \
    + ["english-contractions.10", "english-contractions.35"]
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SWIFT = os.path.join(ROOT, "Sources/KotibaCore/EnglishWords.swift")
TS = os.path.join(ROOT, "windows/src/core/routing/english-words.ts")
CACHE = os.path.expanduser(os.environ.get("KOTIBA_SCOWL_CACHE", "~/.cache/kotiba-scowl.tar.gz"))


def tarball() -> bytes:
    if not os.path.exists(CACHE):
        os.makedirs(os.path.dirname(CACHE), exist_ok=True)
        urllib.request.urlretrieve(URL, CACHE)
    data = open(CACHE, "rb").read()
    got = hashlib.sha256(data).hexdigest()
    if got != SHA256:
        sys.exit(f"{CACHE} is {got}, expected {SHA256} — not the SCOWL release this list is from")
    return data


def words() -> list[str]:
    kept = {"i"}
    with tarfile.open(fileobj=io.BytesIO(tarball()), mode="r:gz") as tar:
        for member in MEMBERS:
            raw = tar.extractfile(f"scowl-2020.12.07/final/{member}").read().decode("latin-1")
            for word in raw.split("\n"):
                word = word.strip()
                if word and word.islower() and not word.endswith("'s"):
                    kept.add(word)
    return sorted(kept)


def render(ws: list[str]) -> tuple[str, str]:
    body = "\n".join(ws)
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    head = (
        "GENERATED by Scripts/english-words.py from SCOWL 2020.12.07 (levels 10-35, English and\n"
        "American, plus contractions; LICENSES/SCOWL.txt). Do not edit — regenerate.\n"
        f"{len(ws)} words, sha256 of the newline-joined list {digest}."
    )
    swift = (
        "".join(f"// {line}\n" for line in head.split("\n"))
        + "\n/// The list `TranscriptCheck` looks words up in. One lowercase word per line, sorted.\n"
        + "enum EnglishWords {\n"
        + f"    static let count = {len(ws)}\n"
        + f"    static let sha256 = \"{digest}\"\n"
        + "    static let text = #\"\"\"\n" + body + "\n\"\"\"#\n}\n"
    )
    ts = (
        "".join(f"// {line}\n" for line in head.split("\n"))
        + "\n/** The list `transcriptCheck` looks words up in. One lowercase word per line, sorted. */\n"
        + f"export const ENGLISH_WORDS_COUNT = {len(ws)};\n"
        + f"export const ENGLISH_WORDS_SHA256 = '{digest}';\n"
        + "export const ENGLISH_WORDS = `" + body + "`;\n"
    )
    return swift, ts


def main() -> None:
    swift, ts = render(words())
    if "--check" in sys.argv:
        stale = [p for p, text in ((SWIFT, swift), (TS, ts))
                 if not os.path.exists(p) or open(p, encoding="utf-8").read() != text]
        if stale:
            sys.exit("stale: " + ", ".join(os.path.relpath(p, ROOT) for p in stale))
        print("english-words: both copies current")
        return
    for path, text in ((SWIFT, swift), (TS, ts)):
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
        print("wrote", os.path.relpath(path, ROOT))


if __name__ == "__main__":
    main()
