#!/usr/bin/env python3
"""Regenerate the Uzbek, Turkish, Russian and Arabic word lists the language decision reads
transcripts against (`Lexicon`, KotibaCore; docs/research/P4-language-id.md §3).

    python3 Scripts/lexicons.py            # writes both platforms' copies
    python3 Scripts/lexicons.py --check    # exits 1 if any copy is stale

Source: the Common Voice sentence collector (`server/data/<locale>/sentence-collector.txt` of
github.com/common-voice/common-voice, pinned below). Every sentence in it was submitted under the
CC0 1.0 public-domain dedication — which is why these lists can ship in an MIT app with no notice
at all (THIRD_PARTY_NOTICES §5 names them anyway).

Every word form the sentences contain, folded the way `Lexicon.fold` folds a transcript's words:
  * the apostrophes ’ ‘ ʻ ʼ ` all become ' (Uzbek writes oʻ/gʻ and the tutuq with any of them);
  * Turkish: İ → i and I → ı before lowercasing, then ı → i (a transcript's dotless i is not
    something a word list should hinge on);
  * Russian: ё → е;
  * Arabic: the tashkeel and the tatweel removed, أ إ آ ٱ → ا, ى → ي, ة → ه;
  * then lowercased; only words written wholly in the language's own script are kept.
All forms, not only the frequent ones: on the tuning half, dropping the singletons took real
Russian's median coverage from 0.80 to 0.73 and real Uzbek's 10th percentile from 0.67 to 0.60,
while separating nothing better (P4 §3).
"""
import hashlib
import os
import re
import sys
import unicodedata
import urllib.request

COMMIT = "ff32a0e4ce705faf36aa7e635c73729227bdcb62"
URL = ("https://raw.githubusercontent.com/common-voice/common-voice/"
       + COMMIT + "/server/data/{locale}/sentence-collector.txt")
SHA256 = {
    "uz": "ac040f9b89d619a2c90a92590ee1489446bf295d8806f4bf746a48f7cffc8048",
    "tr": "28e2d0955f640d001dd90c6205c1e55cde18528a2bed45cc99389bc0d4058ece",
    "ru": "e0869a008310c452f63fd02e4d52f8abc58df2de73e558c486719161e3ad1b87",
    "ar": "438817d8a0de050edfe4d1da10c7b3d9d77702db44d446f9e08e53f012f6e27e",
}
NAMES = {"uz": ("Uzbek", "uzbek"), "tr": ("Turkish", "turkish"), "ru": ("Russian", "russian"),
         "ar": ("Arabic", "arabic")}
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.expanduser(os.environ.get("KOTIBA_CV_CACHE", "~/.cache/kotiba-cv"))

APOSTROPHES = "’‘ʻʼ`"
TASHKEEL = re.compile("[ؐ-ًؚ-ٰٟۖ-ۭـ]")


def source(locale: str) -> str:
    path = os.path.join(CACHE, f"{COMMIT[:12]}-{locale}.txt")
    if not os.path.exists(path):
        os.makedirs(CACHE, exist_ok=True)
        urllib.request.urlretrieve(URL.format(locale=locale), path)
    data = open(path, "rb").read()
    got = hashlib.sha256(data).hexdigest()
    if got != SHA256[locale]:
        sys.exit(f"{path} is {got}, expected {SHA256[locale]} — not the pinned sentence file")
    return unicodedata.normalize("NFC", data.decode("utf-8"))


def fold(locale: str, word: str) -> str:
    for a in APOSTROPHES:
        word = word.replace(a, "'")
    if locale == "tr":
        word = word.replace("İ", "i").replace("I", "ı")
    if locale == "ar":
        word = TASHKEEL.sub("", word)
    word = word.lower()
    if locale == "tr":
        word = word.replace("ı", "i")
    elif locale == "ru":
        word = word.replace("ё", "е")
    elif locale == "ar":
        word = re.sub("[أإآٱ]", "ا", word).replace("ى", "ي").replace("ة", "ه")
    return word


def in_script(locale: str, word: str) -> bool:
    letters = [c for c in word if c != "'"]
    if not letters:
        return False
    if locale in ("uz", "tr"):
        return all("a" <= c <= "z" or "À" <= c <= "ɏ" for c in letters)
    if locale == "ru":
        return all("а" <= c <= "я" for c in letters)
    return all("ؠ" <= c <= "ي" or "ٱ" <= c <= "ۓ" for c in letters)


def words(locale: str) -> list[str]:
    text = source(locale)
    if locale == "ar":
        text = TASHKEEL.sub("", text)
    for a in APOSTROPHES:
        text = text.replace(a, "'")
    kept = set()
    # A word: letters, with ' allowed between two letters — `TranscriptCheck.words(scalarsOf:)`.
    for m in re.finditer(r"[^\W\d_]+(?:'[^\W\d_]+)*", text):
        w = fold(locale, m.group(0))
        if in_script(locale, w):
            kept.add(w)
    return sorted(kept)


def render(locale: str, ws: list[str]) -> tuple[str, str]:
    name, stem = NAMES[locale]
    body = "\n".join(ws)
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    head = (
        f"GENERATED by Scripts/lexicons.py from the Common Voice sentence collector ({locale},\n"
        f"commit {COMMIT[:12]}, CC0-1.0). Do not edit — regenerate.\n"
        f"{len(ws)} words, sha256 of the newline-joined list {digest}."
    )
    swift = (
        "".join(f"// {line}\n" for line in head.split("\n"))
        + f"\n/// Every {name} word form the sentences contain, folded as `Lexicon.fold` folds.\n"
        + f"enum {name}Words {{\n"
        + f"    static let count = {len(ws)}\n"
        + f"    static let sha256 = \"{digest}\"\n"
        + "    static let text = #\"\"\"\n" + body + "\n\"\"\"#\n}\n"
    )
    upper = name.upper()
    ts = (
        "".join(f"// {line}\n" for line in head.split("\n"))
        + f"\n/** Every {name} word form the sentences contain, folded as `lexiconFold` folds. */\n"
        + f"export const {upper}_WORDS_COUNT = {len(ws)};\n"
        + f"export const {upper}_WORDS_SHA256 = '{digest}';\n"
        + f"export const {upper}_WORDS = `" + body + "`;\n"
    )
    return swift, ts


def main() -> None:
    stale = []
    for locale, (name, stem) in NAMES.items():
        swift, ts = render(locale, words(locale))
        targets = ((os.path.join(ROOT, f"Sources/KotibaCore/{name}Words.swift"), swift),
                   (os.path.join(ROOT, f"windows/src/core/routing/{stem}-words.ts"), ts))
        for path, text in targets:
            if "--check" in sys.argv:
                if not os.path.exists(path) or open(path, encoding="utf-8").read() != text:
                    stale.append(os.path.relpath(path, ROOT))
            else:
                with open(path, "w", encoding="utf-8") as f:
                    f.write(text)
                print("wrote", os.path.relpath(path, ROOT))
    if "--check" in sys.argv:
        if stale:
            sys.exit("stale: " + ", ".join(stale))
        print("lexicons: every copy current")


if __name__ == "__main__":
    main()
